### ISSUE TITLE
Fail to build with Qt 6.8.2

### ISSUE THREAD

**Issue by eribertomota** [exeldro/obs-transition-table#27]
Dear @exeldro,

This plugin fails to build from source on Debian with OBS 30.2.3 and Qt 6.8.2.

```
/PKGS/obs-transition-table/obs-transition-table-0.2.7/transition-table.cpp: In constructor ‘TransitionTableDialog::TransitionTableDialog(QMainWindow*)’:
/PKGS/obs-transition-table/obs-transition-table-0.2.7/transition-table.cpp:549:39: error: ‘void QCheckBox::stateChanged(int)’ is deprecated: Use checkStateChanged() instead [-Werror=deprecated-declarations]
  549 |         connect(checkbox, &QCheckBox::stateChanged,
      |                                       ^~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt6/QtWidgets/QCheckBox:1,
                 from /PKGS/obs-transition-table/obs-transition-table-0.2.7/transition-table.hpp:4,
                 from /PKGS/obs-transition-table/obs-transition-table-0.2.7/transition-table.cpp:2:
/usr/include/x86_64-linux-gnu/qt6/QtWidgets/qcheckbox.h:41:10: note: declared here
   41 |     void stateChanged(int);
      |          ^~~~~~~~~~~~
```

Please, see a CI Test here[1].

[1] https://salsa.debian.org/debian/obs-transition-table/-/jobs/7219221

Regards,

Eriberto

**Comment by exeldro** [comment]
That should be fixed by https://github.com/exeldro/obs-transition-table/commit/640a30fb7bfc164d72ac4513bc1f9b9c54ba7d06

**Comment by eribertomota** [comment]
Sure! It worked perfectly. Thanks again.
